### PR TITLE
CSS to eliminate extra printed page, and reorganize closing tags

### PR DESCRIPTION
**Pull request by jrwarwick**
html elements body and html moved to end of document, past modal forms. Style section moved to css file, where a custom media query main form hiding rule was added (tested on recent Chromium). Also css file given some html5boilerplate.com print media styles thrown in. 

Seems to have resolved extraneous page print issue, but only tested on Chromium on Linux. # #9

### CODE REVIEW

**Comment by jrwarwick** [comment]
I performed my own test merging of this series of branches and discovered a conflict. While diligently rechecking-out back to master (synced to upstream) for each topic branch, I ended up introducing an add/add conflict in this pull request. 

To resolve, I ended up rebasing a copy of this branch to the rolling test-merge branch, with bias for the latest introduced version of already-added file. I then went back and checked out the now "obliterated" edition of the file and copied it out to a temp location and switched back to my rebased-and-now-conflict-free-yet-missing-some-history topic branch, and used vimdiff to create the "union" of the versions of the file, commit.  I am not sure if there is a more proper way to do it, but I am pretty confident I have correct results.

However, this is obviously a bit of a headache for upstream, but would be a headache to unwind if you choose not accept intermediate pull requests. Therefore, I will just standby for now, to see which predecessor pull requests are accepted. If you accept all the intermediate pull requests, I will fix this one up in the same manner. Otherwise I will probably need to close, rework and refile.

**Review by retroredge — COMMENTED** [review]
Hi Justin. All the intermediate pull requests. Nick

**Comment by retroredge** [comment]
Hi Justin. My comment above should have read 'All the intermediate pull requests accepted'. 

Nick

**Comment by jrwarwick** [comment]
Thanks, Nick. I will prep and revise the branch (which I think will be automatically reflected in the pull request). 
- Justin

**Comment by jrwarwick** [comment]
Ok, that rebasing was not as clean and neat as I had expected. However, I think the results are "correct" and while the network graph also is not as neat and clean as might be preferred I think it also reflects a safe position to move forward. Please consider this pull request fully submitted.

**Comment by jrwarwick** [comment]
Nick sorry for this hassle, but now as I look at the summary in this pull request, there are some repeats of previous commits. I just performed a local test merge, and it went fine, correctly identifying all of those already-applied changes and skipping them. However, it does make the displayed set of changes noisy and misleading. 

I do still find every indication that the merge would work correctly and without problem, but if you wish for me to close this pull request, delete the branch and create a true fresh branch based on current master, I will do that.

**Comment by retroredge** [comment]
Thank you Justin. It looks fine to me. I tested the printing in Chrome on OSX and the fix works. Good work, that extra page bug was a hard one to track down.

**Pull request merged**
