### PR TITLE
Add basic tooltips consisting of desc for edges and abilities. Via attribute

### PR DESCRIPTION
**Pull request by jrwarwick**
This will add the ability to do a "mouse cursor hover" and get the description displayed as a floating tooltip. Implementation is simply adding in the html element attribute "title" into the NG template.

This feature is not well supported on mobile browsers yet. But there may be some javascript/css technique that could work similarly. Saving that for some research and a future modification.

### CODE REVIEW

**Comment by jrwarwick** [comment]
Sorry, I have done some more reading and realize now that **everything** should get its own branch in my fork if i want to submit pull request. I am going to close this, revert, _branch_ then reapply and resubmit pull requests.

**Comment by retroredge** [comment]
These changes look fine. I like the tooltip idea.

I'll merge them into master.

Nick

**Comment by retroredge** [comment]
Hi Justin.

Coincidentally I was just looking at your changes and testing them locally.
I was about to merge them into master but then noticed you were closing
them. I'll wait until you've re-submitted the pull requests.

After my local merge it looked like three separate commits in the history
which I think would have been OK. But it may be better to put each change
in its own branch in case the owner wants to reject some changes and take
the others.

This is my first pull request merge on GitHub buddy so we're both new to
this :-)

Nick

**Comment by jrwarwick** [comment]
Thanks for your patience and your time. I am going to do just exactly what you've described; one change per branch. More coming.
- Justin

**Pull request closed without merging**
